##################### Filebeat Configuration Example #########################
# https://www.elastic.co/guide/en/beats/filebeat/index.html

#=========================== Filebeat prospectors =============================

filebeat.prospectors:

- input_type: log

  paths:
    - /var/log/nginx/tls-access.log
    - /var/log/nginx/logs-error.log
  document_type: nginx-access

  #exclude_lines: ["^DBG"]
  #include_lines: ["^ERR", "^WARN"]
  #exclude_files: [".gz$"]
  #fields:
  #  level: debug
  #  review: 1

  ### Multiline options
  #multiline.pattern: ^\[
  #multiline.negate: false
  #multiline.match: after

#================================ General =====================================

#name:
#tags: ["service-X", "web-tier"]
#fields:
#  env: staging

#================================ Outputs =====================================

#-------------------------- Elasticsearch output ------------------------------
#output.elasticsearch:
  #hosts: ["elk.owaspsummit.org:9200"]
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["elk.owaspsummit.org:5044"]
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
  #ssl.certificate: "/etc/pki/client/cert.pem"
  #ssl.key: "/etc/pki/client/cert.key"

#================================ Logging =====================================
#logging.level: debug
#logging.selectors: ["*"]
