name: Owasp Summit 2017
markdown: kramdown
data_dir: website/_data
includes_dir: website/_includes
layouts_dir:  website/_layouts
#gems:
#  - jekyll-feed
exclude:
  - CNAME
  - LICENSE
  - node_modules
  - gulpfile.js
  - package.json
  - params.json
  - README.md
  - Logistics/archive
  - website/_temp_files
  - Participants
  - Working-Sessions
  - pages/for-editors
