name: Owasp Summit 2017
markdown: kramdown
includes_dir: website/_includes
layouts_dir:  website/_layouts
exclude:
  - CNAME
  - LICENSE
  - node_modules
  - gulpfile.js
  - package.json
  - params.json
  - README.md
  - Logistics/archive
  - website/_temp_files
